// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZmnNAyT6-7opGkk8mYgrpsIAj1HVt4pM',
    appId: '1:492104718322:web:aabc7f80b68cb2275abd6b',
    messagingSenderId: '492104718322',
    projectId: 'demo6-63fbc',
    authDomain: 'demo6-63fbc.firebaseapp.com',
    storageBucket: 'demo6-63fbc.firebasestorage.app',
    measurementId: 'G-T0QPF3680S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaq6s21bV4BoN1EJKGu5ckryjN00hTOII',
    appId: '1:492104718322:android:cb49efdcaee160a75abd6b',
    messagingSenderId: '492104718322',
    projectId: 'demo6-63fbc',
    storageBucket: 'demo6-63fbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx6I5J2IjLIpMtHwyTLUU0TfVYsGmpMy4',
    appId: '1:492104718322:ios:32b98d75a5dc12b25abd6b',
    messagingSenderId: '492104718322',
    projectId: 'demo6-63fbc',
    storageBucket: 'demo6-63fbc.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx6I5J2IjLIpMtHwyTLUU0TfVYsGmpMy4',
    appId: '1:492104718322:ios:32b98d75a5dc12b25abd6b',
    messagingSenderId: '492104718322',
    projectId: 'demo6-63fbc',
    storageBucket: 'demo6-63fbc.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZmnNAyT6-7opGkk8mYgrpsIAj1HVt4pM',
    appId: '1:492104718322:web:2e9767ce5a4e0c535abd6b',
    messagingSenderId: '492104718322',
    projectId: 'demo6-63fbc',
    authDomain: 'demo6-63fbc.firebaseapp.com',
    storageBucket: 'demo6-63fbc.firebasestorage.app',
    measurementId: 'G-BPD76GD2JZ',
  );
}
